name: Pull-request-master

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1.4.2
      with:
        java-version: 1.8
    
    - name: Build the library
      run: ./gradlew clean :simplepdfviewer:build --stacktrace

    - name: Build the example app
      run: ./gradlew build --stacktrace
