name: Pull-request-master

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1.4.2
      with:
        java-version: 1.8
    
    - name: Build the library
      run: ./gradlew clean :simplepdfviewer:build --stacktrace

    - name: Build the example app
      run: ./gradlew build --stacktrace
  
  unit-tests:
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1.4.2
      with:
        java-version: 1.8
    
    - name: Unit tests
      run: ./gradlew :simplepdfviewer:test --stacktrace
  
  instrumented-tests:
    runs-on: macos-latest
    needs: [unit-tests]
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Instrumented tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: ./gradlew :simplepdfviewer:connectedAndroidTest --stacktrace
